package:
  name: c_scs
  version: 1.0.2

source:
  git_url: https://github.com/cvxgrp/scs

build:
  number: 0

requirements:
  build:
    - system  [linux]
  run:
    - system  [linux]

about:
  home: https://github.com/cvxgrp/scs
  license: MIT