package:
  name: scs
  version: 1.0.2

build:
  number: 0

source:
  git_url: https://github.com/cvxgrp/scs

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - scs
about:
  home: https://github.com/cvxgrp/scs
  license: MIT
  summary: C package that solves convex cone problems via operator splitting